version: "3"

services:
  ##############################
  #SETUP NODE SERVER
  #############################
  server:
    build: ./NodeServer
    expose:
      - 80
    environment:
      API_HOST: "http://localhost:80/"
      APP_SERVER_PORT: 8080
    ports:
      - 8080:80
    volumes:
      - ./app
    command: npm start

  ##########################
  # SETUP CLIENT CONTAINER
  #########################
  client:
    build: ./frontend
    stdin_open: true
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - "./:/src"
    command: npm start
