version: "3"

services:
  ##############################
  #SETUP NODE SERVER
  #############################
  server:
    build: ./NodeServer
    expose:
      - 3000
    environment:
      API_HOST: "http://localhost:3000/"
      APP_SERVER_PORT: 8080
    ports:
      - 8080:3000
    volumes:
      - ./NodeServer/app
    command: npm start

  ##########################
  # SETUP CLIENT CONTAINER
  #########################
  client:
    build: ./frontend
    expose:
      - 3006
    environment:
      API_HOST: localhost
      APP_SERVER_PORT: 9000
    ports:
      - 9000:3006
    volumes:
      - ./frontend/scr/index.js
    command: npm start
