apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: hello1
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: hello1
    tier: frontend
  ports:
    - protocol: TCP
      name: http
      port: 9000
      targetPort: 3000
