apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 80
